#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC7125C934883BE5 (me@adamj.eu)
#
Name     : flake8-comprehensions
Version  : 1.4.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/34/07/cd53c9ae3275f5f52c5ec196b36b3cd5a71e943b199cef18ffaaf4761338/flake8-comprehensions-1.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/34/07/cd53c9ae3275f5f52c5ec196b36b3cd5a71e943b199cef18ffaaf4761338/flake8-comprehensions-1.4.1.tar.gz
Source99 : https://files.pythonhosted.org/packages/34/07/cd53c9ae3275f5f52c5ec196b36b3cd5a71e943b199cef18ffaaf4761338/flake8-comprehensions-1.4.1.tar.gz.asc
Summary  : A flake8 plugin to help you write better list/set/dict comprehensions.
Group    : Development/Tools
License  : ISC ISCL
Requires: flake8-comprehensions-python3
Requires: flake8-comprehensions-license
Requires: flake8-comprehensions-python
Requires: flake8
BuildRequires : buildreq-distutils3
BuildRequires : flake8

%description
flake8-comprehensions
        =====================

%package license
Summary: license components for the flake8-comprehensions package.
Group: Default

%description license
license components for the flake8-comprehensions package.


%package python
Summary: python components for the flake8-comprehensions package.
Group: Default
Requires: flake8-comprehensions-python3

%description python
python components for the flake8-comprehensions package.


%package python3
Summary: python3 components for the flake8-comprehensions package.
Group: Default
Requires: python3-core

%description python3
python3 components for the flake8-comprehensions package.


%prep
%setup -q -n flake8-comprehensions-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533152279
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flake8-comprehensions
cp LICENSE %{buildroot}/usr/share/doc/flake8-comprehensions/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/flake8-comprehensions/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
